services:
  postgres:
    image: docker.io/postgres:13.4
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgresql://postgres:postgres@localhost:5432/database_name" ]
      interval: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_name
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - "./postgresql.conf:/etc/postgresql/postgresql.conf"
      - "postgres_data:/var/lib/postgresql/data/"

  pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    ports:
      - "127.0.0.1:6432:6432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgresql://postgres:postgres@localhost:6432/database_name" ]
      interval: 5s
    # environment:
      # POSTGRESQL_USERNAME: postgres
      # POSTGRESQL_PASSWORD: postgres
      # POSTGRESQL_DATABASE: database_name
      # POSTGRESQL_HOST: postgres
      # POSTGRESQL_PORT: 5432
    entrypoint: pgbouncer
    command: /pgbouncer.ini
    volumes:
      - "./pgbouncer.ini:/pgbouncer.ini:ro"
      - "./pgbouncer_auth_file.txt:/userlist.txt:ro"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

