services:
  postgres:
    image: docker.io/postgres:13.4
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgresql://postgres:postgres@localhost:5432/database_name" ]
      interval: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_name
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - "./postgresql.conf:/etc/postgresql/postgresql.conf"
      - "postgres_data:/var/lib/postgresql/data/"

  pgcat:
    # image: ghcr.io/postgresml/pgcat:1f2c6507f7fb5461df1a599c0b380aa114597bb5 # v1.1.1
    image: ghcr.io/postgresml/pgcat:v1.2.0
    ports:
      - "127.0.0.1:9930:9930"
      - "127.0.0.1:6432:6432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgresql://postgres:postgres@localhost:6432/database_name" ]
      interval: 5s
    entrypoint: bash -c "pgcat /etc/pgcat/pgcat.toml"
    volumes:
      - "./pgcat.toml:/etc/pgcat/pgcat.toml"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
