[general]
host = "0.0.0.0"
port = 6432

# Whether to enable prometheus exporter or not.
enable_prometheus_exporter = true

# Port at which prometheus exporter listens on.
prometheus_exporter_port = 9930

# How long to wait before aborting a server connection (ms).
connect_timeout = 5000

# How much time to give `SELECT 1` health check query to return with a result (ms).
healthcheck_timeout = 1000

# How long to keep connection available for immediate re-use, without running a healthcheck query on it
healthcheck_delay = 30000

# How much time to give clients during shutdown before forcibly killing client connections (ms).
shutdown_timeout = 60000

# For how long to ban a server if it fails a health check (seconds).
ban_time = 60 # seconds

# If we should log client connections
log_client_connections = false

# If we should log client disconnections
log_client_disconnections = false

admin_username = "pgadmin"
admin_password = "pUnogvUJF31VyBm"

[pools.database_name.users.0]
username = "postgres"
password = '''postgres'''
server_username = "postgres"
server_password = '''postgres'''
pool_size = 1
min_pool_size = 1
pool_mode = "transaction"

[pools.database_name.users.1]
username = "postgres-session"
password = '''postgres-session'''
server_username = "postgres"
server_password = '''postgres'''
pool_size = 1
min_pool_size = 1
pool_mode = "session"

[pools.database_name.shards.0]
servers = [
  ["postgres", 5432, "primary"]
]
database = "database_name"
